server:
  port: 8082

spring:
  application:
    name: algoy-ai

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  data:
    mongodb:
      uri: mongodb://algoy_admin:0000@43.203.235.252:27017/algoy_ai?authSource=admin

ai:
  api:
    url: https://kdt-api-function.azurewebsites.net/api/v1/question/sse-streaming
    key: 9158381d-b009-4891-8982-51a6a8dac707