server:
  port: 8082

allowed-connection:
  url: ${ALLOWED_CONNECTION_URL}


spring:
  profiles:
    active: default
  application:
    name: algoy-ai

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  data:
    mongodb:
      uri: ${MONGODB_URI}

ai:
  api:
    url: ${AI_API_URL}
    key: ${AI_API_KEY}

allenApi:
  url: https://kdt-api-function.azurewebsites.net/api/v1/question?content=
  key: 32d9ab5a-aeab-4814-81ac-68d7c0bbbb1d

solvedac:
  url: https://solved.ac/api/v3/user/top_100?handle=