server:
  port: 8082

spring:
  profiles:
    active: default
  application:
    name: algoy-ai

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  data:
    mongodb:
      uri: mongodb://algoy_admin:0000@43.203.235.252:27017/algoy_ai?authSource=admin

ai:
  api:
    url: https://kdt-api-function.azurewebsites.net/api/v1/question/sse-streaming
    key: f6c2c7c5-d7c8-49c7-bf30-a2a6bdc28548

allenApi:
  url: https://kdt-api-function.azurewebsites.net/api/v1/question?content=
  key: 32d9ab5a-aeab-4814-81ac-68d7c0bbbb1d

solvedac:
  url: https://solved.ac/api/v3/user/top_100?handle=